# Site settings
title: Hi, I'm Taylor.
description: Taylor' professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Taylor Martinez
user_title: Dr.
user_job_title: Data Scientist
email: tm.taylormartinez [at] gmail.com
github_username:  tam002

exclude: ['package.json', 'src' , 'node_modules']
